#!/bin/bash
Read num1, num2, num3
If (num1 < num2)
 If(num2 < num3)
 Write num1 , num2, num3
 Else
 If(num3 < num1)
 Write num3, num1, num2
 Else
 Write num1, num3, num2
else
 If(num1 < num3)
 Write num2 , num1, num3
 Else
 If(num3 < num2)
 Write num3, num2, num1
 Else
 Write num2, num3, num1
CH code:
int num1, num2, num3;
cin>> num1>>num2>>num3;
if (num1 < num2)
{ if(num2 < num3)
 { Cout<< num1<<" "<<num2<<" "<<num3; }
 else
 { if(num3 < num1)
 { Cout<< num3<<" "<<num2<<" "<<num2; }
 else
 { Cout<< num1<<" "<<num3<<" "<<num2; }
 }
}
else
