#!/usr/bin/env bash
# Script for Nginx server
sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/^\W*#.*/d' /etc/nginx/sites-available/default
sudo sed -i '/^\W*location \/ {.*/!b;/^/a\\t  add_header X-Served-By \$Hostname;' /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx restart

