#!/usr/bin/env bash
#Displays the current running processes.
#Must show all processes, for all users, including those which might not have a TTY.
#Display in a user-oriented format
#Show process hierarchy

ps -faux
