#!/usr/bin/env bash
#Displays indefinitely writes "I am alive
#Displays in between every"I am alive" message, the program should pause for 2 seconds.

while true
do
      echo "I am alive!" > /tmp/my_process
      sleep 2
done
