#!/usr/bin/env bash
#display Best School 10 times.

count=0
while [ $count -lt 13 ]
do
    echo "Hour: $count"
       count=$(((count+1)))

    minutes=1
    while [ $minutes -lt 60 ]
    do
	    echo "$minutes"
	    minutes=$(((minutes+1)))
    done 
done 
