#!/usr/bin/env bash
#displays information about the school.

count=school
if [ -e "$count" ]
then
    echo "school file exists"
    if [ ! -s "$count" ]
    then
	echo "school file is empty"
	else
	    echo "school file is not empty"
	fi
	if [ -f "$count" ]
	then
	    echo "school is a regular file"
	fi
else
    echo "school file does not exist"
fi	
